server:
  port: 8009
  compression:
    enabled: true
    mime-types: application/json
#    min-response-size: 10KB

spring:
  application:
    name: book-service

security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:8005/oauth/token_key
      id: book-service

eureka:
  instance:
    hostname: localhost
    port: ${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/