server:
  port: 8013

spring:
  application:
    name: library-web
  thymeleaf:
    cache: false
#  main:
#    allow-bean-definition-overriding: true
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /webjars/**, /js/**, /css/** # Make sure the webjars folders are included
      enabled: true
    cache:
      cachecontrol:
        cache-public: true
        max-age: 365D
    static-locations: classpath:/META-INF/resources/webjars/, classpath:/static/ # Make sure the webjars folders are included

eureka:
  instance:
    hostname: localhost
    port: ${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    user-web:
      path: /user/**
      service-id: user-web
