server:
  port: 8017
spring:
  application:
    name: oauth2-server-web
#security:
#  oauth2:
#    client:
#      client-id: client1
#      client-secret: secret


#key-store:
#  path: classpath:keys.jks
#  alias: oauth2jwt
#  key-pass: secret
security:
  oauth2:
    authorization:
      jwt:
        key-store: classpath:keys.jks
        key-alias: oauth2jwt
        key-store-password: secret